apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-api
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: xray-api
  template:
    metadata:
      labels:
        app: xray-api
    spec:
      containers:
      - name: xray-api
        image: appars/xray-api:v1
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
